<a href="https://colab.research.google.com/github/Davron030901/Pandas/blob/main/Pandas_exercises.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [2]:
!wget https://github.com/Davron030901/Pandas/blob/main/data/forbes.csv

--2024-11-29 15:28:04--  https://github.com/Davron030901/Pandas/blob/main/data/forbes.csv
Resolving github.com (github.com)... 140.82.121.4
Connecting to github.com (github.com)|140.82.121.4|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: unspecified [text/html]
Saving to: ‘forbes.csv.1’

forbes.csv.1            [ <=>                ] 497.94K  --.-KB/s    in 0.04s

2024-11-29 15:28:05 (13.0 MB/s) - ‘forbes.csv.1’ saved [509889]

In [5]:
df=pd.read_csv('forbes.csv')
df

,Unnamed: 0,Rank,Company,Country,Sales,Profits,Assets,Market Value,Sector,Industry
0,NaN,1,ICBC,China,151.400,42.000,3473.2,229.800,Financials,Major Banks
1,NaN,2,China Construction Bank,China,134.200,35.000,3016.6,200.500,Financials,Regional Banks
2,NaN,3,Berkshire Hathaway,United States,222.900,24.100,620.9,409.900,Financials,Investment Services
3,NaN,4,JPMorgan Chase,United States,102.500,24.200,2513.0,306.600,Financials,Major Banks
4,NaN,5,Wells Fargo,United States,97.600,21.900,1943.4,274.400,Financials,Major Banks
...,...,...,...,...,...,...,...,...,...,...
1995,NaN,1996,BEKB-BCBE,Switzerland,0.555,0.131,27.9,1.700,Financials,Regional Banks
1996,NaN,1997,Fastighets Balder,Sweden,0.630,0.639,10.2,3.800,Materials,NaN
1997,NaN,1998,Akamai Technologies,United States,2.300,0.316,4.4,10.100,Information Technology,Computer Services
1998,NaN,1999,Oita Bank,Japan,0.523,0.071,27.9,0.595,Financials,Regional Banks
1999,NaN,2000,Tech Mahindra,India,4.200,0.469,3.6,6.700,Information Technology,NaN

In [6]:
df.head()

,Unnamed: 0,Rank,Company,Country,Sales,Profits,Assets,Market Value,Sector,Industry
0,NaN,1,ICBC,China,151.4,42.0,3473.2,229.8,Financials,Major Banks
1,NaN,2,China Construction Bank,China,134.2,35.0,3016.6,200.5,Financials,Regional Banks
2,NaN,3,Berkshire Hathaway,United States,222.9,24.1,620.9,409.9,Financials,Investment Services
3,NaN,4,JPMorgan Chase,United States,102.5,24.2,2513.0,306.6,Financials,Major Banks
4,NaN,5,Wells Fargo,United States,97.6,21.9,1943.4,274.4,Financials,Major Banks

In [7]:
df.head(2)

,Unnamed: 0,Rank,Company,Country,Sales,Profits,Assets,Market Value,Sector,Industry
0,NaN,1,ICBC,China,151.4,42.0,3473.2,229.8,Financials,Major Banks
1,NaN,2,China Construction Bank,China,134.2,35.0,3016.6,200.5,Financials,Regional Banks

In [8]:
df.tail()

,Unnamed: 0,Rank,Company,Country,Sales,Profits,Assets,Market Value,Sector,Industry
1995,NaN,1996,BEKB-BCBE,Switzerland,0.555,0.131,27.9,1.700,Financials,Regional Banks
1996,NaN,1997,Fastighets Balder,Sweden,0.630,0.639,10.2,3.800,Materials,NaN
1997,NaN,1998,Akamai Technologies,United States,2.300,0.316,4.4,10.100,Information Technology,Computer Services
1998,NaN,1999,Oita Bank,Japan,0.523,0.071,27.9,0.595,Financials,Regional Banks
1999,NaN,2000,Tech Mahindra,India,4.200,0.469,3.6,6.700,Information Technology,NaN

In [9]:
df.tail(7)

,Unnamed: 0,Rank,Company,Country,Sales,Profits,Assets,Market Value,Sector,Industry
1993,NaN,1994,Shaanxi Coal Industry,China,3.800,-0.024,13.6,9.000,Materials,Diversified Metals & Mining
1994,NaN,1995,Aurubis,Germany,10.600,0.249,4.5,3.100,Materials,Diversified Metals & Mining
1995,NaN,1996,BEKB-BCBE,Switzerland,0.555,0.131,27.9,1.700,Financials,Regional Banks
1996,NaN,1997,Fastighets Balder,Sweden,0.630,0.639,10.2,3.800,Materials,NaN
1997,NaN,1998,Akamai Technologies,United States,2.300,0.316,4.4,10.100,Information Technology,Computer Services
1998,NaN,1999,Oita Bank,Japan,0.523,0.071,27.9,0.595,Financials,Regional Banks
1999,NaN,2000,Tech Mahindra,India,4.200,0.469,3.6,6.700,Information Technology,NaN

In [11]:
df.sample()

,Unnamed: 0,Rank,Company,Country,Sales,Profits,Assets,Market Value,Sector,Industry
706,NaN,707,Textron,United States,13.8,0.962,15.4,12.9,Industrials,Conglomerates

In [12]:
df.sample(6)

,Unnamed: 0,Rank,Company,Country,Sales,Profits,Assets,Market Value,Sector,Industry
1962,NaN,1963,Associated Banc-Corp,United States,1.2,0.198,29.3,3.6,Financials,NaN
108,NaN,109,Chubb,Switzerland,31.9,4.100,159.8,64.0,Financials,Property & Casualty Insurance
471,NaN,472,Colgate-Palmolive,United States,15.2,2.400,12.1,64.9,Consumer Staples,Household/Personal Care
1892,NaN,1893,Leidos,United States,7.0,0.240,9.1,7.6,NaN,NaN
1007,NaN,1008,Nielsen,United States,6.3,0.502,15.7,14.9,NaN,NaN
1890,NaN,1891,Sumitomo Rubber,Japan,7.0,0.381,7.7,4.5,Consumer Discretionary,Auto & Truck Parts

In [13]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2000 entries, 0 to 1999
Data columns (total 10 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   Unnamed: 0    0 non-null      float64
 1    Rank         2000 non-null   int64
 2   Company       2000 non-null   object
 3   Country       2000 non-null   object
 4   Sales         2000 non-null   float64
 5   Profits       2000 non-null   float64
 6   Assets        2000 non-null   float64
 7   Market Value  2000 non-null   float64
 8   Sector        1803 non-null   object
 9   Industry      1509 non-null   object
dtypes: float64(5), int64(1), object(4)
memory usage: 156.4+ KB

In [25]:
df.select_dtypes(include=['int', 'float']).info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2000 entries, 0 to 1999
Data columns (total 6 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   Unnamed: 0    0 non-null      float64
 1    Rank         2000 non-null   int64
 2   Sales         2000 non-null   float64
 3   Profits       2000 non-null   float64
 4   Assets        2000 non-null   float64
 5   Market Value  2000 non-null   float64
dtypes: float64(5), int64(1)
memory usage: 93.9 KB

In [24]:
df.select_dtypes(include=['object']).info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2000 entries, 0 to 1999
Data columns (total 4 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   Company   2000 non-null   object
 1   Country   2000 non-null   object
 2   Sector    1803 non-null   object
 3   Industry  1509 non-null   object
dtypes: object(4)
memory usage: 62.6+ KB

In [26]:
df.select_dtypes(include=['bool']).info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2000 entries, 0 to 1999
Empty DataFrame

In [31]:
df.sort_values('Market Value', ascending=False).head(8)

,Unnamed: 0,Rank,Company,Country,Sales,Profits,Assets,Market Value,Sector,Industry
8,NaN,9,Apple,United States,217.5,45.2,331.1,752.0,Information Technology,Computer Hardware
23,NaN,24,Alphabet,United States,89.9,19.5,167.5,579.5,Information Technology,NaN
18,NaN,19,Microsoft,United States,85.3,16.8,224.6,507.5,Information Technology,Software & Programming
82,NaN,83,Amazon.com,United States,136.0,2.4,86.0,427.0,Consumer Discretionary,Internet & Catalog Retail
2,NaN,3,Berkshire Hathaway,United States,222.9,24.1,620.9,409.9,Financials,Investment Services
118,NaN,119,Facebook,United States,27.6,9.5,65.0,407.3,Information Technology,Computer Services
12,NaN,13,Exxon Mobil,United States,197.5,7.8,330.3,343.2,Energy,NaN
31,NaN,32,Johnson & Johnson,United States,71.9,16.4,141.2,338.6,Health Care,Medical Equipment & Supplies

In [33]:
df.sort_values('Market Value').head(6)

,Unnamed: 0,Rank,Company,Country,Sales,Profits,Assets,Market Value,Sector,Industry
1796,NaN,1797,Grupo Zuliano,Venezuela,1.000,0.999,1.5,0.072,NaN,NaN
1726,NaN,1727,Bank of Greece,Greece,1.900,1.200,10.0,0.240,Financials,Major Banks
1006,NaN,1007,Finatis,France,40.700,-2.500,46.0,0.292,Consumer Staples,Food Retail
1623,NaN,1624,Moscovskiy Oblastnoi Bank,Russia,2.600,1.700,4.5,0.363,Financials,NaN
1239,NaN,1240,Dexia,Belgium,0.393,0.417,224.4,0.373,Financials,Major Banks
1577,NaN,1578,Intelsat,Luxembourg,2.200,0.990,12.9,0.504,NaN,NaN

In [42]:
pd.set_option('display.max_rows', 8)

In [43]:
pd.set_option('display.max_columns', 6)

In [37]:
df

,Unnamed: 0,Rank,Company,Country,...,Assets,Market Value,Sector,Industry
0,NaN,1,ICBC,China,...,3473.2,229.800,Financials,Major Banks
1,NaN,2,China Construction Bank,China,...,3016.6,200.500,Financials,Regional Banks
2,NaN,3,Berkshire Hathaway,United States,...,620.9,409.900,Financials,Investment Services
...,...,...,...,...,...,...,...,...,...
1997,NaN,1998,Akamai Technologies,United States,...,4.4,10.100,Information Technology,Computer Services
1998,NaN,1999,Oita Bank,Japan,...,27.9,0.595,Financials,Regional Banks
1999,NaN,2000,Tech Mahindra,India,...,3.6,6.700,Information Technology,NaN

In [47]:
pd.set_option('display.max_column',20)

In [48]:
pd.set_option('display.max_rows',60)

In [46]:
df

,Unnamed: 0,Rank,Company,Country,Sales,Profits,Assets,Market Value,Sector,Industry
0,NaN,1,ICBC,China,151.400,42.000,3473.2,229.800,Financials,Major Banks
1,NaN,2,China Construction Bank,China,134.200,35.000,3016.6,200.500,Financials,Regional Banks
2,NaN,3,Berkshire Hathaway,United States,222.900,24.100,620.9,409.900,Financials,Investment Services
3,NaN,4,JPMorgan Chase,United States,102.500,24.200,2513.0,306.600,Financials,Major Banks
4,NaN,5,Wells Fargo,United States,97.600,21.900,1943.4,274.400,Financials,Major Banks
...,...,...,...,...,...,...,...,...,...,...
1995,NaN,1996,BEKB-BCBE,Switzerland,0.555,0.131,27.9,1.700,Financials,Regional Banks
1996,NaN,1997,Fastighets Balder,Sweden,0.630,0.639,10.2,3.800,Materials,NaN
1997,NaN,1998,Akamai Technologies,United States,2.300,0.316,4.4,10.100,Information Technology,Computer Services
1998,NaN,1999,Oita Bank,Japan,0.523,0.071,27.9,0.595,Financials,Regional Banks
1999,NaN,2000,Tech Mahindra,India,4.200,0.469,3.6,6.700,Information Technology,NaN

In [53]:
df.shape

(2000, 10)

In [54]:
df.shape[0]

2000

In [55]:
len(df)

2000

In [56]:
df.shape[1]

10

In [58]:
df.columns

Index(['Unnamed: 0', ' Rank', 'Company', 'Country', 'Sales', 'Profits',
       'Assets', 'Market Value', 'Sector', 'Industry'],
      dtype='object')

In [59]:
df.columns.to_list()

['Unnamed: 0',
 ' Rank',
 'Company',
 'Country',
 'Sales',
 'Profits',
 'Assets',
 'Market Value',
 'Sector',
 'Industry']

In [62]:
df.index

RangeIndex(start=0, stop=2000, step=1)

In [64]:
df['Country']

0               China
1               China
2       United States
3       United States
4       United States
            ...
1995      Switzerland
1996           Sweden
1997    United States
1998            Japan
1999            India
Name: Country, Length: 2000, dtype: object

In [65]:
len(df['Country'])

2000

In [66]:
len(df['Sector'])

2000

In [76]:
df["Market Value"][::-1]

1999      6.700
1998      0.595
1997     10.100
1996      3.800
1995      1.700
         ...
4       274.400
3       306.600
2       409.900
1       200.500
0       229.800
Name: Market Value, Length: 2000, dtype: float64

In [77]:
df["Market Value"].iloc[::-1]

1999      6.700
1998      0.595
1997     10.100
1996      3.800
1995      1.700
         ...
4       274.400
3       306.600
2       409.900
1       200.500
0       229.800
Name: Market Value, Length: 2000, dtype: float64

In [87]:
# df["Market Value"]
df["Market Value"].sort_values()

1796      0.072
1726      0.240
1006      0.292
1623      0.363
1239      0.373
         ...
2       409.900
82      427.000
18      507.500
23      579.500
8       752.000
Name: Market Value, Length: 2000, dtype: float64

In [86]:
df[' Rank']

0          1
1          2
2          3
3          4
4          5
        ...
1995    1996
1996    1997
1997    1998
1998    1999
1999    2000
Name:  Rank, Length: 2000, dtype: int64

In [92]:
df.isnull()
df.isna()

,Unnamed: 0,Rank,Company,Country,Sales,Profits,Assets,Market Value,Sector,Industry
0,True,False,False,False,False,False,False,False,False,False
1,True,False,False,False,False,False,False,False,False,False
2,True,False,False,False,False,False,False,False,False,False
3,True,False,False,False,False,False,False,False,False,False
4,True,False,False,False,False,False,False,False,False,False
...,...,...,...,...,...,...,...,...,...,...
1995,True,False,False,False,False,False,False,False,False,False
1996,True,False,False,False,False,False,False,False,False,True
1997,True,False,False,False,False,False,False,False,False,False
1998,True,False,False,False,False,False,False,False,False,False
1999,True,False,False,False,False,False,False,False,False,True

In [98]:
df.isna().sum()/len(df)*100

Unnamed: 0      100.00
 Rank             0.00
Company           0.00
Country           0.00
Sales             0.00
Profits           0.00
Assets            0.00
Market Value      0.00
Sector            9.85
Industry         24.55
dtype: float64

In [104]:
a=df.shape[0]
a

2000

In [112]:
df1=df.dropna()
df1

Empty DataFrame
Columns: [Unnamed: 0,  Rank, Company, Country, Sales, Profits, Assets, Market Value, Sector, Industry]
Index: []

In [115]:
(len(df)-len(df1))/len(df)*100

100.0

In [116]:
df1.isnull().sum()

Unnamed: 0      0
 Rank           0
Company         0
Country         0
Sales           0
Profits         0
Assets          0
Market Value    0
Sector          0
Industry        0
dtype: int64

In [118]:
df2=df.dropna(axis=0)
df2
len(df2)

0

In [121]:
df2=df.dropna(axis=1)
df2.shape[1]

7

In [122]:
df3=df2.dropna(axis=0)
df3

,Rank,Company,Country,Sales,Profits,Assets,Market Value
0,1,ICBC,China,151.400,42.000,3473.2,229.800
1,2,China Construction Bank,China,134.200,35.000,3016.6,200.500
2,3,Berkshire Hathaway,United States,222.900,24.100,620.9,409.900
3,4,JPMorgan Chase,United States,102.500,24.200,2513.0,306.600
4,5,Wells Fargo,United States,97.600,21.900,1943.4,274.400
...,...,...,...,...,...,...,...
1995,1996,BEKB-BCBE,Switzerland,0.555,0.131,27.9,1.700
1996,1997,Fastighets Balder,Sweden,0.630,0.639,10.2,3.800
1997,1998,Akamai Technologies,United States,2.300,0.316,4.4,10.100
1998,1999,Oita Bank,Japan,0.523,0.071,27.9,0.595
1999,2000,Tech Mahindra,India,4.200,0.469,3.6,6.700

In [124]:
df4=df.dropna(subset=['Sector','Industry'])
df4

,Unnamed: 0,Rank,Company,Country,Sales,Profits,Assets,Market Value,Sector,Industry
0,NaN,1,ICBC,China,151.400,42.000,3473.2,229.800,Financials,Major Banks
1,NaN,2,China Construction Bank,China,134.200,35.000,3016.6,200.500,Financials,Regional Banks
2,NaN,3,Berkshire Hathaway,United States,222.900,24.100,620.9,409.900,Financials,Investment Services
3,NaN,4,JPMorgan Chase,United States,102.500,24.200,2513.0,306.600,Financials,Major Banks
4,NaN,5,Wells Fargo,United States,97.600,21.900,1943.4,274.400,Financials,Major Banks
...,...,...,...,...,...,...,...,...,...,...
1993,NaN,1994,Shaanxi Coal Industry,China,3.800,-0.024,13.6,9.000,Materials,Diversified Metals & Mining
1994,NaN,1995,Aurubis,Germany,10.600,0.249,4.5,3.100,Materials,Diversified Metals & Mining
1995,NaN,1996,BEKB-BCBE,Switzerland,0.555,0.131,27.9,1.700,Financials,Regional Banks
1997,NaN,1998,Akamai Technologies,United States,2.300,0.316,4.4,10.100,Information Technology,Computer Services
1998,NaN,1999,Oita Bank,Japan,0.523,0.071,27.9,0.595,Financials,Regional Banks

In [125]:
df4.isnull().sum()

Unnamed: 0      1508
 Rank              0
Company            0
Country            0
Sales              0
Profits            0
Assets             0
Market Value       0
Sector             0
Industry           0
dtype: int64

In [126]:
df2=df.fillna(1)
df2

,Unnamed: 0,Rank,Company,Country,Sales,Profits,Assets,Market Value,Sector,Industry
0,1.0,1,ICBC,China,151.400,42.000,3473.2,229.800,Financials,Major Banks
1,1.0,2,China Construction Bank,China,134.200,35.000,3016.6,200.500,Financials,Regional Banks
2,1.0,3,Berkshire Hathaway,United States,222.900,24.100,620.9,409.900,Financials,Investment Services
3,1.0,4,JPMorgan Chase,United States,102.500,24.200,2513.0,306.600,Financials,Major Banks
4,1.0,5,Wells Fargo,United States,97.600,21.900,1943.4,274.400,Financials,Major Banks
...,...,...,...,...,...,...,...,...,...,...
1995,1.0,1996,BEKB-BCBE,Switzerland,0.555,0.131,27.9,1.700,Financials,Regional Banks
1996,1.0,1997,Fastighets Balder,Sweden,0.630,0.639,10.2,3.800,Materials,1
1997,1.0,1998,Akamai Technologies,United States,2.300,0.316,4.4,10.100,Information Technology,Computer Services
1998,1.0,1999,Oita Bank,Japan,0.523,0.071,27.9,0.595,Financials,Regional Banks
1999,1.0,2000,Tech Mahindra,India,4.200,0.469,3.6,6.700,Information Technology,1

In [127]:
df2.isnull().sum()

Unnamed: 0      0
 Rank           0
Company         0
Country         0
Sales           0
Profits         0
Assets          0
Market Value    0
Sector          0
Industry        0
dtype: int64

In [128]:
df.tail()

,Unnamed: 0,Rank,Company,Country,Sales,Profits,Assets,Market Value,Sector,Industry
1995,NaN,1996,BEKB-BCBE,Switzerland,0.555,0.131,27.9,1.700,Financials,Regional Banks
1996,NaN,1997,Fastighets Balder,Sweden,0.630,0.639,10.2,3.800,Materials,NaN
1997,NaN,1998,Akamai Technologies,United States,2.300,0.316,4.4,10.100,Information Technology,Computer Services
1998,NaN,1999,Oita Bank,Japan,0.523,0.071,27.9,0.595,Financials,Regional Banks
1999,NaN,2000,Tech Mahindra,India,4.200,0.469,3.6,6.700,Information Technology,NaN

In [129]:
df3=df.fillna(method='ffill')
df3.tail()

<ipython-input-129-d1e46d1adbfd>:1: FutureWarning: DataFrame.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  df3=df.fillna(method='ffill')

,Unnamed: 0,Rank,Company,Country,Sales,Profits,Assets,Market Value,Sector,Industry
1995,NaN,1996,BEKB-BCBE,Switzerland,0.555,0.131,27.9,1.700,Financials,Regional Banks
1996,NaN,1997,Fastighets Balder,Sweden,0.630,0.639,10.2,3.800,Materials,Regional Banks
1997,NaN,1998,Akamai Technologies,United States,2.300,0.316,4.4,10.100,Information Technology,Computer Services
1998,NaN,1999,Oita Bank,Japan,0.523,0.071,27.9,0.595,Financials,Regional Banks
1999,NaN,2000,Tech Mahindra,India,4.200,0.469,3.6,6.700,Information Technology,Regional Banks

In [130]:
df4=df.fillna(method='bfill')
df4.tail()

<ipython-input-130-14fcb0eba96e>:1: FutureWarning: DataFrame.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  df4=df.fillna(method='bfill')

,Unnamed: 0,Rank,Company,Country,Sales,Profits,Assets,Market Value,Sector,Industry
1995,NaN,1996,BEKB-BCBE,Switzerland,0.555,0.131,27.9,1.700,Financials,Regional Banks
1996,NaN,1997,Fastighets Balder,Sweden,0.630,0.639,10.2,3.800,Materials,Computer Services
1997,NaN,1998,Akamai Technologies,United States,2.300,0.316,4.4,10.100,Information Technology,Computer Services
1998,NaN,1999,Oita Bank,Japan,0.523,0.071,27.9,0.595,Financials,Regional Banks
1999,NaN,2000,Tech Mahindra,India,4.200,0.469,3.6,6.700,Information Technology,NaN

In [136]:
df['Unnamed: 0'].fillna(1, inplace=True)
df

<ipython-input-136-20db868e65bb>:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['Unnamed: 0'].fillna(1, inplace=True)

,Unnamed: 0,Rank,Company,Country,Sales,Profits,Assets,Market Value,Sector,Industry
0,1.0,1,ICBC,China,151.400,42.000,3473.2,229.800,Financials,Major Banks
1,1.0,2,China Construction Bank,China,134.200,35.000,3016.6,200.500,Financials,Regional Banks
2,1.0,3,Berkshire Hathaway,United States,222.900,24.100,620.9,409.900,Financials,Investment Services
3,1.0,4,JPMorgan Chase,United States,102.500,24.200,2513.0,306.600,Financials,Major Banks
4,1.0,5,Wells Fargo,United States,97.600,21.900,1943.4,274.400,Financials,Major Banks
...,...,...,...,...,...,...,...,...,...,...
1995,1.0,1996,BEKB-BCBE,Switzerland,0.555,0.131,27.9,1.700,Financials,Regional Banks
1996,1.0,1997,Fastighets Balder,Sweden,0.630,0.639,10.2,3.800,Materials,NaN
1997,1.0,1998,Akamai Technologies,United States,2.300,0.316,4.4,10.100,Information Technology,Computer Services
1998,1.0,1999,Oita Bank,Japan,0.523,0.071,27.9,0.595,Financials,Regional Banks
1999,1.0,2000,Tech Mahindra,India,4.200,0.469,3.6,6.700,Information Technology,NaN

In [138]:
df.fillna(df.mean())
df

TypeError: can only concatenate str (not "int") to str

In [149]:
df["Assets"]=df["Assets"].astype(int)
df

,Unnamed: 0,Rank,Company,Country,Sales,Profits,Assets,Market Value,Sector,Industry
0,1.0,1.0,ICBC,China,151.400,42.000,3473,229.800,Financials,Major Banks
1,1.0,2.0,China Construction Bank,China,134.200,35.000,3016,200.500,Financials,Regional Banks
2,1.0,3.0,Berkshire Hathaway,United States,222.900,24.100,620,409.900,Financials,Investment Services
3,1.0,4.0,JPMorgan Chase,United States,102.500,24.200,2513,306.600,Financials,Major Banks
4,1.0,5.0,Wells Fargo,United States,97.600,21.900,1943,274.400,Financials,Major Banks
...,...,...,...,...,...,...,...,...,...,...
1995,1.0,1996.0,BEKB-BCBE,Switzerland,0.555,0.131,27,1.700,Financials,Regional Banks
1996,1.0,1997.0,Fastighets Balder,Sweden,0.630,0.639,10,3.800,Materials,NaN
1997,1.0,1998.0,Akamai Technologies,United States,2.300,0.316,4,10.100,Information Technology,Computer Services
1998,1.0,1999.0,Oita Bank,Japan,0.523,0.071,27,0.595,Financials,Regional Banks
1999,1.0,2000.0,Tech Mahindra,India,4.200,0.469,3,6.700,Information Technology,NaN

In [150]:
df[' Rank']=df[' Rank'].astype(float)
df

,Unnamed: 0,Rank,Company,Country,Sales,Profits,Assets,Market Value,Sector,Industry
0,1.0,1.0,ICBC,China,151.400,42.000,3473,229.800,Financials,Major Banks
1,1.0,2.0,China Construction Bank,China,134.200,35.000,3016,200.500,Financials,Regional Banks
2,1.0,3.0,Berkshire Hathaway,United States,222.900,24.100,620,409.900,Financials,Investment Services
3,1.0,4.0,JPMorgan Chase,United States,102.500,24.200,2513,306.600,Financials,Major Banks
4,1.0,5.0,Wells Fargo,United States,97.600,21.900,1943,274.400,Financials,Major Banks
...,...,...,...,...,...,...,...,...,...,...
1995,1.0,1996.0,BEKB-BCBE,Switzerland,0.555,0.131,27,1.700,Financials,Regional Banks
1996,1.0,1997.0,Fastighets Balder,Sweden,0.630,0.639,10,3.800,Materials,NaN
1997,1.0,1998.0,Akamai Technologies,United States,2.300,0.316,4,10.100,Information Technology,Computer Services
1998,1.0,1999.0,Oita Bank,Japan,0.523,0.071,27,0.595,Financials,Regional Banks
1999,1.0,2000.0,Tech Mahindra,India,4.200,0.469,3,6.700,Information Technology,NaN